#ifndef _ERROR_H
#define _ERROR_H

typedef enum{
  ERR_COLON_MISSING,
  ERR_DATA_CORRUPTED,
  ERR_UNKNOWN_DATA,
  ERR_UNKNOWN_RECORD_TYPE,
  ERR_INVALID_INSTRUCTION_AFTER_EOF,
} ErrorCode;


#endif // _TESTPARSER_H
